services:
  backend:
    build:
      context: backend-project
      dockerfile: ./Dockerfile
    restart: unless-stopped

  frontend:
    build:
      context: react-frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
